### ISSUE TITLE
shell integration conf not respected

### ISSUE THREAD

**Issue by 0ther0ne** [alexpasmantier/television#374]
**Description**

in the conf file I disabled the 'channel/triggers':
`#"dirs" = ["cd", "ls", "rmdir"]`

but the 'CTRL-T' key binding still works even with cd, ls, rmdir

**Environment**
 - OS: Arch Linux
 - Rust version: 1.85.0
 - Project version: 0.10.7
 - bash shell

**Comment by alexpasmantier** [comment]
Thanks for the feedback.

Should be fixed in #417

**Comment by 0ther0ne** [comment]
sorry but I just installed 0.11.4 version,

and the bug is still there

**Comment by alexpasmantier** [comment]
I'm not able to reproduce the issue on 0.11.4.

Have you tried restarting your shell session to make sure any previously set keybindings are cleared out?

**Comment by 0ther0ne** [comment]
yes, I restart the terminal but now 'CTRL-T' key binding works with EVERY terminal command and even WITHOUT any commands  O_o
