### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by iamkavinnnn** [alexpasmantier/television#384]
dpkg-deb: error: unexpected end of file in archive magic version number in television_0.10.7-1_amd64.deb
dpkg: error processing archive television_0.10.7-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 television_0.10.7-1_amd64.deb

I get this error when trying to install it in ubuntu.

**Comment by josulf** [comment]
Same problem here, seems that in the latest version the .deb package has not been published.

**Comment by alexpasmantier** [comment]
Should be fixed by #390 

Will ship with the next patch

**Comment by MadeInShineA** [comment]
I still have this issue using 

```
VER=`curl -s "https://api.github.com/repos/alexpasmantier/television/releases/latest" | grep '"tag_name":' | sed -E 's/.*"tag_name": "([^"]+)".*/\1/'`
curl -LO https://github.com/alexpasmantier/television/releases/download/$VER/television_$VER-1_amd64.deb
echo $VER
sudo dpkg -i television_$VER-1_amd64.deb
```
(It's the readme installation command)

**Comment by alexpasmantier** [comment]
Hi, thanks for the feedback.

Was able to reproduce inside a VM running debian.

The reason for the error seems to be that the latest debian/ubuntu releases ship with a rather old version of `libc` (2.36) whereas `tv` requires >= 2.39.

The current workaround for debian-based users would simply be to use the `musl` build instead which is a static build and should work mostly anywhere.

![Image](https://github.com/user-attachments/assets/1fd4f5f3-7f9a-4879-9a16-3190536a0fcc)

![Image](https://github.com/user-attachments/assets/1f1ddc59-3e54-4844-aaaa-2aa87c84f497)

I'll update the installation snippet accordingly.
